[tool.ruff]
extend-exclude = [
  ".git",       # excluded by default, leaving for example
  "*.pyc",
  "__pycache__",
]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
extend-select = [
   "I",
  "UP",
  # "N",
  # "B",
]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

[tool.poetry]
name = "somr-api"
version = "0.0.1"
description = ""
authors = ["Nova <bakapixel>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "3.12.x"
# general python
mypy = "*"
ruff = "*"

[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]
exclude = ["build", "bin", "obj"]

[[tool.mypy.overrides]]
module = [
  "google.*",
  "pydata_google_auth.*",
  "schema.*",
]
ignore_missing_imports = true
